apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.chartmuseum.env.existingSecret }}
  namespace: {{ .Release.Namespace }}
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.accessSecret }}
